[project]
name = "Ingestion-Service"
version = "0.1.1"
description = "Default template for PDM package"
authors = [
    {name = "Louis903995", email = "louis@moises.fr"},
]
dependencies = ["pyodbc>=5.2.0", "fastapi>=0.116.1", "uvicorn>=0.35.0", "sqlalchemy>=2.0.42", "pydantic>=2.11.7", "sqlmodel>=0.0.24", "mistralai>=1.9.3", "levenshtein>=0.27.1", "python-dotenv>=1.1.1"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
export_requirements = "pdm export -o requirements.txt --without-hashes"
build_docker_image = "bash -c 'VERSION=$(grep -oP \"version = \\\"\\K[^\\\"]+\" pyproject.toml); docker build -t ingestion-service:$VERSION -t ingestion-service:latest .'"
build_docker = { composite = ["export_requirements", "build_docker_image"] }
create_network = "docker network create mon-reseau"
sql_server = "docker run -e \"ACCEPT_EULA=Y\" -e \"MSSQL_SA_PASSWORD=Password123\" -p 1433:1433 --name sql-server-dev --hostname sql-server-dev --network mon-reseau -d mcr.microsoft.com/mssql/server:2025-latest"
container = "docker run --env-file .env.container.local -p 8000:8000 --name ingestion-service --network mon-reseau -d ingestion-service:latest"
deploy = [
  "az acr login --name crsimploncertif",
  "VERSION=$(grep -oP 'version = \"\\K[^\\\"]+' pyproject.toml) && docker tag ingestion-service:$VERSION crsimploncertif.azurecr.io/ingestion-service:$VERSION",
  "VERSION=$(grep -oP 'version = \"\\K[^\\\"]+' pyproject.toml) && docker push crsimploncertif.azurecr.io/ingestion-service:$VERSION"
]


fastapi = "uvicorn app.main:app --reload"
[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Unrecognized server version info.*:sqlalchemy.exc.SAWarning"
]